In [9]:
from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print (data.shape)
print (target.shape)
print (set (target))    

(150, 4)
(150,)
{'setosa', 'virginica', 'versicolor'}


In [10]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [13]:
from sklearn.ensemble import BaggingClassifier
classifier = BaggingClassifier()
classifier.fit(data,t) # training on the iris dataset

BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=1.0,
         n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
         verbose=0, warm_start=False)

In [14]:
print (t[0])

1.0


In [22]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t, test_size=0.2, random_state=0)

In [23]:
classifier.fit(train,t_train) # train
print (classifier.score(test,t_test)) # test

1.0


In [24]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [25]:
classifier.predict(test)

array([ 3.,  2.,  1.,  3.,  1.,  3.,  1.,  2.,  2.,  2.,  3.,  2.,  2.,
        2.,  2.,  1.,  2.,  2.,  1.,  1.,  3.,  2.,  1.,  1.,  3.,  1.,
        1.,  2.,  2.,  1.])

In [26]:
t_test

array([ 3.,  2.,  1.,  3.,  1.,  3.,  1.,  2.,  2.,  2.,  3.,  2.,  2.,
        2.,  2.,  1.,  2.,  2.,  1.,  1.,  3.,  2.,  1.,  1.,  3.,  1.,
        1.,  2.,  2.,  1.])

In [27]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(classifier.predict(test),t_test))

[[11  0  0]
 [ 0 13  0]
 [ 0  0  6]]


In [28]:
from sklearn.metrics import classification_report
print (classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica']))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        11
 versicolor       1.00      1.00      1.00        13
  virginica       1.00      1.00      1.00         6

avg / total       1.00      1.00      1.00        30

