In [1]:
from numpy import genfromtxt, zeros
# read the first 4 columns
data = genfromtxt('iris.csv',delimiter=',',usecols=(0,1,2,3))
# read the fifth column
target = genfromtxt('iris.csv',delimiter=',',usecols=(4),dtype=str)
print (data.shape)
print (target.shape)
print (set (target))    

(150, 4)
(150,)
{'setosa', 'virginica', 'versicolor'}


In [2]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [101]:
from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
clf1 = LogisticRegression(random_state=1)
clf2 = RandomForestClassifier(random_state=1)
clf3 = GaussianNB()
eclf = VotingClassifier(estimators=[('lr', clf1), ('rf', clf2), ('gnb', clf3)], voting='hard')

In [102]:
print (classifier.predict(data[0]))

[ 1.90065707]


C:\Users\kaga\Anaconda3\lib\site-packages\sklearn\utils\validation.py:395: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and will raise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)


In [112]:
from sklearn.ensemble import BaggingClassifier
classifier = BaggingClassifier()
classifier.fit(data,t) # training on the iris dataset

BaggingClassifier(base_estimator=None, bootstrap=True,
         bootstrap_features=False, max_features=1.0, max_samples=1.0,
         n_estimators=10, n_jobs=1, oob_score=False, random_state=None,
         verbose=0, warm_start=False)

In [4]:
print (t[0])

1.0


In [114]:
from sklearn import cross_validation
train, test, t_train, t_test = cross_validation.train_test_split(data, t, test_size=0.4, random_state=0)

In [115]:
classifier.fit(train,t_train) # train
print (classifier.score(test,t_test)) # test

0.883333333333


In [116]:
t = zeros(len(target))
t[target == 'setosa'] = 1
t[target == 'versicolor'] = 2
t[target == 'virginica'] = 3

In [117]:
classifier.predict(test)

array([ 3.,  2.,  1.,  3.,  1.,  3.,  1.,  2.,  2.,  2.,  3.,  2.,  2.,
        2.,  2.,  1.,  2.,  2.,  1.,  1.,  2.,  2.,  1.,  1.,  2.,  1.,
        1.,  2.,  2.,  1.,  3.,  2.,  1.,  2.,  3.,  2.,  1.,  3.,  2.,
        2.,  3.,  1.,  3.,  1.,  1.,  2.,  3.,  3.,  2.,  3.,  2.,  3.,
        2.,  2.,  2.,  3.,  2.,  3.,  2.,  3.])

In [118]:
t_test

array([ 3.,  2.,  1.,  3.,  1.,  3.,  1.,  2.,  2.,  2.,  3.,  2.,  2.,
        2.,  2.,  1.,  2.,  2.,  1.,  1.,  3.,  2.,  1.,  1.,  3.,  1.,
        1.,  2.,  2.,  1.,  3.,  2.,  1.,  3.,  3.,  2.,  1.,  2.,  2.,
        2.,  3.,  1.,  3.,  1.,  1.,  2.,  3.,  3.,  3.,  3.,  2.,  3.,
        2.,  2.,  3.,  3.,  3.,  3.,  2.,  3.])

In [119]:
from sklearn.metrics import confusion_matrix
print (confusion_matrix(classifier.predict(test),t_test))

[[16  0  0]
 [ 0 22  6]
 [ 0  1 15]]


In [120]:
from sklearn.metrics import classification_report
print (classification_report(classifier.predict(test), t_test,
target_names=['setosa', 'versicolor', 'virginica']))

             precision    recall  f1-score   support

     setosa       1.00      1.00      1.00        16
 versicolor       0.96      0.79      0.86        28
  virginica       0.71      0.94      0.81        16

avg / total       0.90      0.88      0.89        60

